### ISSUE TITLE
Support getenvoy CLI on Windows

### ISSUE THREAD

**Issue by sunjayBhatia** [tetratelabs/func-e#105]
With the Alpha release of Envoy on Windows approaching, we think it would be useful for users to eventually be able to use the getenvoy CLI tool to fetch and run Envoy etc. once Envoy on Windows is GA. We are opening this issue is to start the conversation about the steps needed to get to Windows support in getenvoy.

As far as I can tell, the high-level steps I can glean from looking around the getenvoy repos are:
- Augment https://github.com/tetratelabs/getenvoy-package to support building on Windows
- Augment this repo to build the getenvoy CLI on Windows and have it fetch Envoy-Windows builds
- Update documentation to add usage examples for Windows

getenvoy/Tetrate package distribution channels could also be augmented for Windows, distributing Envoy via chocolatey or some other package manager

If there is anything high-level that maintainers of getenvoy see is critical and missing, please let us know (and of course if you are willing to support getenvoy on Windows at all!)

**Comment by sunjayBhatia** [comment]
We're getting close to a Beta release of Envoy on Windows as well, do the maintainers have any thoughts on this work?

**Comment by lizan** [comment]
@sunjayBhatia Sorry for being late on this, yes we definitely love to see Windows support of GetEnvoy! The outline above looks great to me.

**Comment by sunjayBhatia** [comment]
Awesome, thanks @lizan, we will get some PRs going to hopefully incrementally get this going

**Comment by codefromthecrypt** [comment]
we are also using GH actions consistently here, now, and would need to add windows to the matrix for that to work. Are you still interested in contributing?

**Comment by codefromthecrypt** [comment]
It looks like windows is officially supported with the most recent version of envoy. We may be able to play a trick to test this by extracting the binary from the upstream docker image https://blog.envoyproxy.io/general-availability-of-envoy-on-windows-267e4544994a

**Comment by codefromthecrypt** [comment]
added this issue to ask envoy to retain the binaries they already build https://github.com/envoyproxy/envoy/issues/16830

**Comment by sunjayBhatia** [comment]
Sorry unfortunately internal company priorities changed for me so I'm light on time to contribute to this at the moment!

**Comment by codefromthecrypt** [comment]
@sunjayBhatia no problem. Tetrate bought me a windows laptop so I can look into this personally.. and I am now. I hope by the end of the week things will be working even if using a temporary envoy binary tarball. Will make notes here with progress.

**Comment by codefromthecrypt** [comment]
#309 will fix this, but it won't likely merge until next week. If anyone is impatient and has a windows environment with go 1.16.5 installed, you can install it on your own meanwhile!

```bash
GOBIN=$PWD go install  github.com/tetratelabs/func-e@windows-compile
```

**Comment by codefromthecrypt** [comment]
func-e v0.6.0 supports windows

**Comment by codefromthecrypt** [comment]
notes are [here](https://github.com/tetratelabs/func-e/releases/tag/v0.6.0), though we need to complete packaging #316
