### ISSUE TITLE
Error: couldn't find version "1.18.3" for platform "darwin/arm64"

### ISSUE THREAD

**Issue by trujillo-adam** [tetratelabs/func-e#299]
**Describe the bug**
I do not have an Envoy configuration file, so I am using the option to start the admin port. When I run `func-e run` using the JSON provided in the documentation, I get an error.

**To Reproduce**
1. Run ```curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin``` to install func-e
2. Run ```func-e run --config-yaml "admin: {address: {socket_address: {address: '127.0.0.1', port_value: 9901}}}"``` to use the admin port

**Expected behavior**
I expected to get the latest version of Envoy. MacOS should be able to run application for amd64 on Rosetta 2.

**Screenshots**

**Environment (please complete the relevant information):**
 - OS: MacOS 11.3.1 (M1)
 - Envoy Version: n/a

**Comment by karl-cardenas-coding** [comment]
To get around this issue, we created our own manifest file and added an entry for arm64 that simply pointed to the amd64 binary. It's a hack but a workaround.

```
$ export ENVOY_VERSION_URL=https://raw.githubusercontent.com/hashicorp/demo-consul-101/5845000a614aae67c4d94edba2f9ecc2f1a737a6/envoy-manifest.json
$ curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin
$ func-e run --config-yaml "admin: {address: {socket_address: {address: '127.0.0.1', port_value: 9901}}}"
```
maninfest.json
```json
{
  "latestVersion": "1.18.3",
  "versions": {
    "1.18.3": {
      "releaseDate": "2021-05-11",
      "tarballs": {
        "darwin/amd64": "https://archive.tetratelabs.io/envoy/download/v1.18.3/envoy-v1.18.3-darwin-amd64.tar.xz",
        "darwin/arm64": "https://archive.tetratelabs.io/envoy/download/v1.18.3/envoy-v1.18.3-darwin-amd64.tar.xz",
        "linux/amd64": "https://archive.tetratelabs.io/envoy/download/v1.18.3/envoy-v1.18.3-linux-amd64.tar.xz",
        "linux/arm64": "https://archive.tetratelabs.io/envoy/download/v1.18.3/envoy-v1.18.3-linux-arm64.tar.xz",
        "windows/amd64": "https://archive.tetratelabs.io/envoy/download/v1.18.3/envoy-v1.18.3-windows-amd64.tar.xz"
      }
    }
  },
  "sha256sums": {
    "envoy-v1.18.3-darwin-amd64.tar.xz": "cb27be135f0d48167b756d17fa9117ed6295ee3f69e4db7900b94ddffef463e1",
    "envoy-v1.18.3-darwin-arm64.tar.xz": "cb27be135f0d48167b756d17fa9117ed6295ee3f69e4db7900b94ddffef463e1",
    "envoy-v1.18.3-linux-amd64.tar.xz": "10e1c6bc354018578f02c97358d3bbc9a26d4989cf752963611e69dac52656f4",
    "envoy-v1.18.3-linux-arm64.tar.xz": "367d61bf246d56cc24949574977edefa4649ad2072c08d57a8bd63c44d991d25",
    "envoy-v1.18.3-windows-amd64.tar.xz": "1274f55b3022bc1331aed41089f189094e00729981fe132ce00aac6272ea0770"  
  }
}
```

**Comment by codefromthecrypt** [comment]
interesting and wow thanks for sharing. I didn't know about this work-around.

Is there a way we can detect presence of Rosetta until someone [fixes the envoy build and make arm64 work by default](https://github.com/envoyproxy/envoy/issues/16482) cc @musaprg

easy ways would be a file with a stable path, an ENV variable or output from a command like `uname` that would change if Rosetta 2 is installed

**Comment by codefromthecrypt** [comment]
I found this, though it might be a little hairy because for example, envoy should be fixed at some point and we'd have to know that the intent is to run emulated or not.

https://github.com/electron-userland/electron-builder/blob/71d37044d348ab0cd8f0f9f7754bf6ebaa4b996c/packages/electron-updater/src/MacUpdater.ts#L33-L41

**Comment by codefromthecrypt** [comment]
one way is we could force the platform. This would remove ambiguity at the cost of being explicit. @trujillo-adam would you hate it if you specified `--platform darwin/amd64` or some env? At least until we find a solid way to detect and test this..

**Comment by karl-cardenas-coding** [comment]
@codefromthecrypt We discussed this option, and we think having the ability to specify a platform would be neat. This could be an environment variable. Adding it as an environment would be pretty easy to implement.

**Comment by codefromthecrypt** [comment]
cool. let's do it now a global flag (app.go) and carried around in GlobalOpts. Global flag avoids mushing flags envoy should read and also makes sure `use` and `list` operate properly.

ex --platform and FUNC_E_PLATFORM which populate GlobalOpts.Platform, defaulted to GlobalOpts.CurrentPlatform. GlobalOpts.CurrentPlatform is no longer read at call sites because GlobalOpts.Platform is

would you like to go for it or should I?

**Comment by karl-cardenas-coding** [comment]
@codefromthecrypt I might be wrong, but I think we still need to add some logic to `installIfNeeded()`, mainly because of this logic:

```go

		tarballURL := ev.Versions[v].Tarballs[p] // Ensure there is a version for this platform
		if tarballURL == "" {
			return "", fmt.Errorf("couldn't find version %q for platform %q", v, p)
		}
		
```
It can default to GlobalOpts.Platform

**Comment by codefromthecrypt** [comment]
The main logic change is signatures like this:

```
o, globals.CurrentPlatform
```
to
```
o
```

as `o.Platform` will be available. In other words the result of this change is that globals.CurrentPlatform is only read once, to default the flag when empty. To do that indeed is some signature refactoring!

**Comment by codefromthecrypt** [comment]
all logic is intentionally internal, so it isn't a problem to change the signatures in other words, even on a patch release.
