### ISSUE TITLE
There seems to be a problem with the install.sh script

### ISSUE THREAD

**Issue by kunTom** [tetratelabs/func-e#322]
**Describe the bug**
When running the  " curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin " or "   curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin  0.6.0"
it always returns 
"tetratelabs/func-e crit unable to find '0.6.0' - use 'latest' or see https://github.com/tetratelabs/func-e/releases for details"

**Comment by codefromthecrypt** [comment]
can you mention your output of `uname -a` or which operating system you are using? also `curl --version`

 note func-e is a default package in home-brew for linux and macOS https://formulae.brew.sh/formula/func-e#default

**Comment by kunTom** [comment]
![image](https://user-images.githubusercontent.com/87972694/128030848-52ae9e6a-1bf9-409c-a821-bb26a2ea8175.png)

**Comment by codefromthecrypt** [comment]
thanks. I'll re-open the issue though as it should work. I'll at least verify this in a docker image similar to yours.

**Comment by codefromthecrypt** [comment]
sorry can you clarify which OS and version this is?

**Comment by kunTom** [comment]
> sorry can you clarify which OS and version this is?

sorry，it works right now,but I don't konw why.The day after I submited issue ,I found it works,so I closed issue. And sorry for your waiting a long time .
