### ISSUE TITLE
Hi! Is this still being updated and maintained? any planned roadmap?

### ISSUE THREAD

**Issue by nathanawmk** [tetratelabs/func-e#369]
Hi! Is this still being updated and maintained? any planned roadmap?

**Comment by codefromthecrypt** [comment]
thanks for asking! we are actively working on this project and it is mainly [issues bound]
(https://github.com/tetratelabs/func-e/issues). In other words, there isn't a roadmap as we try to keep things nimble and solve problems as they arise or are reported to us.

We typically release code frequently (1-2 months tops). The next release will support "latest patch" syntax #360, thanks to @dio and also we will try to get linux packages in as well.

If you feel something is lacking, raise an issue, or you can also [watch the repo](https://github.com/tetratelabs/func-e/watchers) which will alert you about things requested or completed, including [releases](https://github.com/tetratelabs/func-e/releases).

Hope this answers your question!
