### ISSUE TITLE
Release asset for 0.7.0-linux-arm64 temporarily unreachable

### ISSUE THREAD

**Issue by hidai** [tetratelabs/func-e#374]
**Describe the bug**
The download link of ARM64 binary is broken:
https://github.com/tetratelabs/func-e/releases/download/v0.7.0/func-e_0.7.0_linux_arm64.tar.gz

The broken link is listed in https://github.com/tetratelabs/func-e/releases/tag/v0.7.0 .

**To Reproduce**
1. Download install.sh from https://func-e.io/install.sh
1. Run the install.sh in a ARM64 machine
2. Error!

**Expected behavior**
install.sh works in ARM64 machines.

**Environment (please complete the relevant information):**
 - OS: Ubuntu 20.04 for ARM64

**Comment by mathetake** [comment]
thanks for reporting this. We are looking into this right now, but looks like this issue is not limited to this repository's release asserts; I found the seemingly relevant issues raised in the portal: https://github.community/t/signaturedoesnotmatch-error-downloading-release/202138/2

**Comment by mathetake** [comment]
OK, this is no longer a problem - GitHuh has deployed the fix. Closing.
