### ISSUE TITLE
Unable to run func-e on MacOS BigSur 11.1 (20C69)

### ISSUE THREAD

**Issue by Mozuffer** [tetratelabs/func-e#432]
Hi Guys, I’m trying to install func-e [v1.1.3](https://github.com/tetratelabs/func-e/releases/tag/v1.1.3) on MacOS BigSur version 11.1 (20C69) and it shows the following error when I run func-e with the envoy config

$ func-e run -c envoydirectresponse-210927-161048.yaml
looking up the latest Envoy version
downloading https://archive.tetratelabs.io/envoy/download/v1.22.2/envoy-v1.22.2-darwin-amd64.tar.xz
starting: /Users/mozufferhago/.func-e/versions/1.22.2/bin/envoy -c envoydirectresponse-210927-161048.yaml --admin-address-path /Users/mozufferhago/.func-e/runs/1658224236473888000/admin-address.txt
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/mozufferhago/.func-e/versions/1.22.2/bin/envoy (which was built for Mac OS X 12.3)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/mozufferhago/.func-e/versions/1.22.2/bin/envoy

envoydirectresponse-210927-161048.yaml:
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: hello_world_service
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: my_first_route
            virtual_hosts:
            - name: direct_response_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "yay"

**Comment by codefromthecrypt** [comment]
This is a problem in envoy itself. It stopped supporting MacOS 11 starting in 1.21.1 https://github.com/tetratelabs/archive-envoy/pull/42

You'll have to use an earlier version of Envoy or upgrade your host.
