### ISSUE TITLE
Allow to use system provided envoy

### ISSUE THREAD

**Issue by chenrui333** [tetratelabs/func-e#438]
**Describe the bug**
Right now, func-e only install and run the specified envoy by itself, which caused some issue as

```
==> /opt/homebrew/Cellar/func-e/1.1.4/bin/func-e run --version
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /private/tmp/func-e-test-20230105-69203-1bzeb1u/.func-e/versions/1.24.1/bin/envoy (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
```

**To Reproduce**
on macos-11, run `func-e run` 

version: func-e 1.14
os: macOS 11
envoy: 1.24.1

**Expected behavior**
It should runs out fine.

**Additional context**
relates to https://github.com/Homebrew/homebrew-core/pull/119899

**Comment by codefromthecrypt** [comment]
func-e's CLI was made to pass arguments literally to envoy, so not sure what value there is making a feature for this. e.g. `func-e run xxxx` calls `envoy xxxx`.

func-e can only support versions of envoy that the archive uses, and it recently dropped support for MacOS 11 https://github.com/tetratelabs/archive-envoy/pull/42

**Comment by chenrui333** [comment]
Closing as we dropped macos-11 support. Thanks @codefromthecrypt!
