### ISSUE TITLE
Is there a better way to add envoy to an existing alpine image?

### ISSUE THREAD

**Issue by noahehall** [tetratelabs/func-e#439]
**Is your feature request related to a problem? Please describe.**

- i'm always frustrated when I copypasta a blob from duckerhub to get func-e install to work

**Describe the solution you'd like**
- func-e installs envoy on alpine

**Describe alternatives you've considered**

- i copypastaed a blob from envoyproxy-alpine image to get func-e install to work

**Additional context**

- you can see the copypasta here: https://github.com/nirv-ai/configs/blob/develop/docker/core/vault/vault.compose.Dockerfile#L49

**Comment by codefromthecrypt** [comment]
func-e is a glorified shell script that runs envoy. The root concern here, I think, are the dependencies envoy needs to run on alpine. There may be an existing issue on https://github.com/envoyproxy/envoy or someone on their chat to help find an alternative bootstrap image? That said, if anyone knows something who is watching this repo, please answer!

**Comment by noahehall** [comment]
@codefromthecrypt  you are indeed, correct.
the use of glibc has been a long felt [toothache for alpine](https://wiki.alpinelinux.org/wiki/Running_glibc_programs).

the mention of `$FUNC_E_PLATFORM` in the funky manpage

```sh
Advanced:
   `FUNC_E_PLATFORM` overrides the host OS and architecture of Envoy binaries.
   This value must be constant within a `$FUNC_E_HOME
```

gave me a wee bit of hope func-e solved this issue, and would match the x86_64 arch of the alpine image

**Comment by codefromthecrypt** [comment]
maybe that flag should clarify it is for emulation. sorry about the false hope on it..

**Comment by noahehall** [comment]
dreams are built on false hopes my friend, thanks for the clarification.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/func-e/pull/440 to help the next person!
