### ISSUE TITLE
Are there any plans to include Envoy contrib versions in func-e?

### ISSUE THREAD

**Issue by ardikabs** [tetratelabs/func-e#450]
**Description**
I am curious if func-e will include Envoy contrib versions in the future. Because when I checked https://archive.tetratelabs.io/envoy/envoy-versions.json, I didn't see any contrib versions listed.

**Comment by codefromthecrypt** [comment]
dupe of https://github.com/tetratelabs/archive-envoy/issues/37 where the last comment was that it would be similar to how debug images are handled, but someone needs to do the work
