### ISSUE TITLE
Missing newer envoy versions past 1.31.0

### ISSUE THREAD

**Issue by NEckes** [tetratelabs/func-e#452]
**Describe the bug**
When I try to install envoy version 1.32.1 func-e I get the message `error: couldn't find version "1.32.1" for platform "linux/arm64"`.
When listing the versions no version past 1.31.0 is available.

**To Reproduce**
1. Run `func-e versions -a`

**Expected behavior**
A list of all released envoy versions (at time of writing up until 1.32.1)

**Environment (please complete the relevant information):**
 - OS: Amazon Linux 2023 on aarch64
 - Envoy Version: -

**Additional context**
When looking into https://archive.tetratelabs.io/envoy/envoy-versions.json the versions seem to be missing at server side.
My source of envoy releases is https://github.com/envoyproxy/envoy/releases.

**Comment by dio** [comment]
Some of these issues are fixed, namely listing all the available versions and setting the correct latest version.
